### ISSUE TITLE
I accidentally broke your mod

### ISSUE THREAD

**Issue by NotNite** [koenjicode/BombRushDiscord#1]
Hi! I released Slop Crew 2.0.0, which features some breaking changes to the API, and in my own incompetence I forgot to version the API and now Slop Crew is crashing on startup if any mods that use the API are installed. This can be fixed by bumping the submodule to the latest commit. My apologies!

**Comment by koenjicode** [comment]
Forgot to close this but it's now fixed in 2.0.0!
